DemoPL/Controllers/DepartmentController.cs
using DemoBLL.Interfaces;
using DemoBLL.Mock_Repositories;
using DemoBLL.Repositories;
using DemoDAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace DemoPL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public DepartmentController(IUnitOfWork unitOfWork)
        {

            _unitOfWork = unitOfWork;
        }

        //Department/Index
        public async Task<IActionResult> Index()
        {
            //// ViewData
            //ViewData["message"] = "Hellow view data";

            //// ViewBag
            //ViewBag.Hamada = "Hellow every one";
 
            var departments =await  _unitOfWork.DepartmentRepository.GetAll();
            return View(departments);
        }
        //[HttpGet]
        public  IActionResult Create()
        {
            return  View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.DepartmentRepository.Add(department);
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        //Department/Details
        public async Task<IActionResult> Details(int? id , string viewName ="Details")
        {
            if (id == null)
                return NotFound();
            var department = await _unitOfWork.DepartmentRepository.Get(id.Value);
            if (department == null)
                return NotFound();
            return View( viewName ,department);

        }
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id , "Edit");
            //if (id == null)
            //    return BadRequest();
            //var department = _departmentRepository.Get(id.Value);
            //if (department == null)
            //    return BadRequest();

            //return View(department);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute]int? id , Department department)
        {
            if (id != department.Id)
                return BadRequest();
            
            if (ModelState.IsValid)
            {
                try
                {
                    await _unitOfWork.DepartmentRepository.Update(department);
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    //return View(department);
                }
            }
            return View(department);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id,"Delete");
            //if (id == null)
            //    return BadRequest();
            //var department = _departmentRepository.Get(id.Value);
            //if (department == null)
            //    return BadRequest();
            //return View(department);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int id,Department department)
        {
            if (id != department.Id )
                return BadRequest();
            try
            {
                await _unitOfWork.DepartmentRepository.Delete(department);
                return RedirectToAction(nameof (Index));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
                return View(department);
            }
        }
    }
}

DemoPL/Controllers/EmployeeController.cs
using AutoMapper;
using DemoBLL.Interfaces;
using DemoDAL.Entities;
using DemoPL.Helpers;
using DemoPL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoPL.Controllers
{
    [Authorize]

    public class EmployeeController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        //Employee/Index
        public async Task<IActionResult> Index(string SearchValue)
        {
            var Employees= Enumerable.Empty<Employee>();

            if (string.IsNullOrEmpty(SearchValue))
            
                Employees =await _unitOfWork.EmployeeRepository.GetAll();
            else
            
                Employees = _unitOfWork.EmployeeRepository.SearchEmployeesByName(SearchValue);
            

            var mappedEmp = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(Employees);

            return View(mappedEmp);

        }
        //[HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await _unitOfWork.DepartmentRepository.GetAll();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid)
            {
                ///Manual Mapping
                ///var mappedEmpm = new Employee() 
                ///{ 
                ///    Name= employeeVM.Name,
                ///    Address= employeeVM.Address,
                ///    Salary= employeeVM.Salary,
                ///    Age= employeeVM.Age,
                ///    IsActive= employeeVM.IsActive,
                ///    Department= employeeVM.Department,
                ///    Email= employeeVM.Email,
                ///    PhoneNumber= employeeVM.PhoneNumber,
                ///};

                employeeVM.ImageName = DocumentSettings.UploadFiles(employeeVM.Image, "images");

                var mappedEmpm = _mapper.Map<EmployeeViewModel , Employee>(employeeVM);

                await _unitOfWork.EmployeeRepository.Add(mappedEmpm);
                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);
        }

        //Employee/Details
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id == null)
                return NotFound();
            var Employee = await _unitOfWork.EmployeeRepository.Get(id.Value);
            if (Employee == null)
                return NotFound();
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(Employee);
            return View(viewName, mappedEmp);

        }
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Departments = await _unitOfWork.DepartmentRepository.GetAll();

            return await Details(id, "Edit");
            //if (id == null)
            //    return BadRequest();
            //var Employee = _EmployeeRepository.Get(id.Value);
            //if (Employee == null)
            //    return BadRequest();

            //return View(Employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id, EmployeeViewModel employeeVM)
        {
            //if (id != employeeVM.Id)
            //    return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                   await _unitOfWork.EmployeeRepository.Update(mappedEmp);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    //return View(Employee);
                }
            }
            return View(employeeVM);
        }

        public async Task<IActionResult>  Delete(int? id)
        {
            return await Details(id, "Delete");
            //if (id == null)
            //    return BadRequest();
            //var Employee = _EmployeeRepository.Get(id.Value);
            //if (Employee == null)
            //    return BadRequest();
            //return View(Employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();
            if (employeeVM is null)
            {
                throw new ArgumentNullException(nameof(employeeVM));
            }

            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel,Employee>(employeeVM);
                int count = await _unitOfWork.EmployeeRepository.Delete(mappedEmp);
                if (count > 0)
                    DocumentSettings.DeleteFile(employeeVM.ImageName, "images");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
                return View(employeeVM);
            }
        }
    }   
}

DemoPL/Controllers/UserController.cs
using DemoBLL.Interfaces;
using DemoDAL.Entities;
using DemoPL.Helpers;
using DemoPL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;

namespace DemoPL.Controllers
{
	public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;

		public UserController(UserManager<ApplicationUser> userManager)
		{
			_userManager = userManager;
		}

        //User/Index
        public async Task<IActionResult> Index(string SearchValue)
        {
            var users = Enumerable.Empty<ApplicationUser>().ToList();
            if (string.IsNullOrEmpty(SearchValue))
                users.AddRange(_userManager.Users);
            else

                users.Add(await _userManager.FindByEmailAsync(SearchValue));
            return View(users);

        }
        //[HttpGet]
        //public async Task<IActionResult> Create()
        //{
        //    ViewBag.Departments = await _unitOfWork.DepartmentRepository.GetAll();
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        ///Manual Mapping
        //        ///var mappedEmpm = new Employee() 
        //        ///{ 
        //        ///    Name= employeeVM.Name,
        //        ///    Address= employeeVM.Address,
        //        ///    Salary= employeeVM.Salary,
        //        ///    Age= employeeVM.Age,
        //        ///    IsActive= employeeVM.IsActive,
        //        ///    Department= employeeVM.Department,
        //        ///    Email= employeeVM.Email,
        //        ///    PhoneNumber= employeeVM.PhoneNumber,
        //        ///};

        //        employeeVM.ImageName = DocumentSettings.UploadFiles(employeeVM.Image, "images");

        //        var mappedEmpm = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

        //        await _unitOfWork.EmployeeRepository.Add(mappedEmpm);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(employeeVM);
        //}

        //Employee/Details

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id == null)
                return NotFound();
            var users = await _userManager.FindByIdAsync(id);
            if (users == null)
                return NotFound();

            return View(viewName, users);

        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
            ///if (id == null)
            ///    return BadRequest();
            ///var Employee = _EmployeeRepository.Get(id.Value);
            ///if (Employee == null)
            ///    return BadRequest();
            ///return View(Employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, ApplicationUser updatedUser)
        {
            if (id != updatedUser.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var user =await _userManager.FindByIdAsync(id);
                    user.UserName = updatedUser.UserName;
                    user.PhoneNumber = updatedUser.PhoneNumber;

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    //return View(Employee);
                }
            }
            return View(updatedUser);
        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
            ///if (id == null)
            ///    return BadRequest();
            ///var Employee = _EmployeeRepository.Get(id.Value);
            ///if (Employee == null)
            ///    return BadRequest();
            ///return View(Employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete( string id, ApplicationUser deletedUser)
        {
            if (id != deletedUser.Id)
                return BadRequest();

            try
            {
                var user = await _userManager.FindByIdAsync(id);

                await _userManager.DeleteAsync(user);// throw exception

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
                return View(deletedUser);
            }
        }
    }
}

DemoPL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib @ViewData["Title"] Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->

	<script src="~/lib/jquery/dist/jquery.min.js"></script> 
	@await RenderSectionAsync("validationScriptSection", required: false)
</body>
</html>

DemoPL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a  asp-action="Details" asp-route-id="@Model" class=" btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class=" btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class=" btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

DemoPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoPL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoPL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Rple" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DemoPL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("validationScriptSection", required: false)
</body>
</html>